[package]
name = "directory-ui-viewer"
version = "0.1.0"
description = "A visual, local-first directory explorer"
authors = ["bigwin22"]
edition = "2024"

[lib]
name = "directory_ui_viewer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }

[dev-dependencies]
libc = "0.2"
